apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30092
  selector:
    name: kafka-mq
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-mq
  labels:
    name: kafka-mq
spec:
  containers:
  - image: wurstmeister/zookeeper
    name: zookeper
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 2181
  - image: wurstmeister/kafka
    name: kafka
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 9092
    env:
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: ":2181"
      - name: KAFKA_ADVERTISED_LISTENERS
        value: "INSIDE://${HOSTIP}:30092"
      - name: KAFKA_LISTENERS
        value: "INSIDE://:9092"
      - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: "INSIDE:PLAINTEXT"
      - name: KAFKA_INTER_BROKER_LISTENER_NAME
        value: "INSIDE"
      - name: KAFKA_CREATE_TOPICS
        value: "test:1:1"
